/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_op_activity_JSRender */

#ifndef _Included_com_op_activity_JSRender
#define _Included_com_op_activity_JSRender
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_op_activity_JSRender
 * Method:    onDrawFrame
 * Signature: (Ljavax/microedition/khronos/opengles/GL10;)V
 */
JNIEXPORT void JNICALL Java_com_op_activity_JSRender_onDrawFrame
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_op_activity_JSRender
 * Method:    onSurfaceChanged
 * Signature: (Ljavax/microedition/khronos/opengles/GL10;II)V
 */
JNIEXPORT void JNICALL Java_com_op_activity_JSRender_onSurfaceChanged
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_op_activity_JSRender
 * Method:    onSurfaceCreated
 * Signature: (Ljavax/microedition/khronos/opengles/GL10;Ljavax/microedition/khronos/egl/EGLConfig;)V
 */
JNIEXPORT void JNICALL Java_com_op_activity_JSRender_onSurfaceCreated
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
