/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_op_activity_JSSurfaceView */

#ifndef _Included_com_op_activity_JSSurfaceView
#define _Included_com_op_activity_JSSurfaceView
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_op_activity_JSSurfaceView
 * Method:    jsPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_op_activity_JSSurfaceView_jsPause
  (JNIEnv *, jclass);

/*
 * Class:     com_op_activity_JSSurfaceView
 * Method:    jsResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_op_activity_JSSurfaceView_jsResume
  (JNIEnv *, jclass);

/*
 * Class:     com_op_activity_JSSurfaceView
 * Method:    jsTouchClick
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_com_op_activity_JSSurfaceView_jsTouchClick
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     com_op_activity_JSSurfaceView
 * Method:    jsTouchMove
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_op_activity_JSSurfaceView_jsTouchMove
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_op_activity_JSSurfaceView
 * Method:    jsKeyBackPress
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_op_activity_JSSurfaceView_jsKeyBackPress
  (JNIEnv *, jclass);

/*
 * Class:     com_op_activity_JSSurfaceView
 * Method:    jsKeyMenuPress
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_op_activity_JSSurfaceView_jsKeyMenuPress
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
