/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_op_activity_JSActivity */

#ifndef _Included_com_op_activity_JSActivity
#define _Included_com_op_activity_JSActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_op_activity_JSActivity
 * Method:    initWithAsset
 * Signature: (Landroid/content/res/AssetManager;)V
 */
JNIEXPORT void JNICALL Java_com_op_activity_JSActivity_initWithAsset
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_op_activity_JSActivity
 * Method:    jsCreate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_op_activity_JSActivity_jsCreate
  (JNIEnv *, jclass);

/*
 * Class:     com_op_activity_JSActivity
 * Method:    jsDestory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_op_activity_JSActivity_jsDestory
  (JNIEnv *, jclass);

/*
 * Class:     com_op_activity_JSActivity
 * Method:    evalScript
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_op_activity_JSActivity_evalScript
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
